// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: usericon.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserIconClient is the client API for UserIcon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserIconClient interface {
	// 获取用户车辆 icon
	GetUserIcon(ctx context.Context, in *UserIconRequest, opts ...grpc.CallOption) (*UserIconResponse, error)
}

type userIconClient struct {
	cc grpc.ClientConnInterface
}

func NewUserIconClient(cc grpc.ClientConnInterface) UserIconClient {
	return &userIconClient{cc}
}

func (c *userIconClient) GetUserIcon(ctx context.Context, in *UserIconRequest, opts ...grpc.CallOption) (*UserIconResponse, error) {
	out := new(UserIconResponse)
	err := c.cc.Invoke(ctx, "/grpc.api.UserIcon/getUserIcon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserIconServer is the server API for UserIcon service.
// All implementations must embed UnimplementedUserIconServer
// for forward compatibility
type UserIconServer interface {
	// 获取用户车辆 icon
	GetUserIcon(context.Context, *UserIconRequest) (*UserIconResponse, error)
	mustEmbedUnimplementedUserIconServer()
}

// UnimplementedUserIconServer must be embedded to have forward compatible implementations.
type UnimplementedUserIconServer struct {
}

func (UnimplementedUserIconServer) GetUserIcon(context.Context, *UserIconRequest) (*UserIconResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserIcon not implemented")
}
func (UnimplementedUserIconServer) mustEmbedUnimplementedUserIconServer() {}

// UnsafeUserIconServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserIconServer will
// result in compilation errors.
type UnsafeUserIconServer interface {
	mustEmbedUnimplementedUserIconServer()
}

func RegisterUserIconServer(s grpc.ServiceRegistrar, srv UserIconServer) {
	s.RegisterService(&UserIcon_ServiceDesc, srv)
}

func _UserIcon_GetUserIcon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserIconServer).GetUserIcon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.api.UserIcon/getUserIcon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserIconServer).GetUserIcon(ctx, req.(*UserIconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserIcon_ServiceDesc is the grpc.ServiceDesc for UserIcon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserIcon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.api.UserIcon",
	HandlerType: (*UserIconServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getUserIcon",
			Handler:    _UserIcon_GetUserIcon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usericon.proto",
}
