CREATE TABLE `author_manuscript_detail` (
                                            `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                            `chapter_id` varchar(64) NOT NULL DEFAULT '' COMMENT '章节id',
                                            `publish_time` varchar(64) NOT NULL DEFAULT '' COMMENT '章节发布时间',
                                            `author_id` varchar(64) NOT NULL DEFAULT '' COMMENT '作者id',
                                            `author_name` varchar(256) NOT NULL DEFAULT '' COMMENT '作者名称',
                                            `space` varchar(256) NOT NULL DEFAULT '' COMMENT '长短篇',
                                            `author_mode` varchar(256) NOT NULL DEFAULT '' COMMENT '作者长篇短篇，内容短篇',
                                            `yesterday_upvote_cnt` bigint(20) NOT NULL DEFAULT '0' COMMENT '昨天点赞数',
                                            `7_day_upvote_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '7天点赞数',
                                            `30d_upvote_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '30天点赞数',
                                            `total_upvote_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '总点赞数',
                                            `yesterday_comment_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '昨天评论数',
                                            `7_day_comment_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '7天评论数',
                                            `30d_comment_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '30天评论数',
                                            `total_comment_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '总天评论数',
                                            `member_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'member_id',
                                            `sku_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'sku_id',
                                            `sku_name` varchar(64) NOT NULL DEFAULT '' COMMENT 'sku_name',
                                            `p_date` varchar(64) NOT NULL DEFAULT '' COMMENT '时间',
                                            `chapter_title` varchar(256) NOT NULL DEFAULT '' COMMENT '章节标题',
                                            `test_type` int(8) NOT NULL DEFAULT '0' COMMENT '实验是否加和',
                                            PRIMARY KEY (`id`),
                                            KEY `idx_member_id` (`member_id`),
                                            KEY `idx_sku_id` (`sku_id`),
                                            KEY `idx_chapter_id` (`chapter_id`),
                                            KEY `idx_p_date` (`p_date`),
                                            KEY `idx_test_type` (`test_type`),
                                            KEY `idx_space` (`space`),
                                            UNIQUE KEY `uniq_author_manuscript_detail` (`member_id`,`chapter_id`,`test_type`,`p_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=53309446 COMMENT='内容域盐选作者文稿页互动明细表 (每日全量)' ;

CREATE TABLE `author` (
                          `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                          `author_type` bigint(20) NOT NULL DEFAULT '0' COMMENT '作者类型',
                          `member_id` bigint(20) DEFAULT '0' COMMENT '站内用户ID',
                          `author_name` varchar(128) NOT NULL DEFAULT '' COMMENT '作者名称',
                          `author_status` int(8) DEFAULT '0' COMMENT '作者状态，0：正常，-1：已删除',
                          `introduce` varchar(2048) NOT NULL DEFAULT '' COMMENT '简介',
                          `avatar` varchar(4096) NOT NULL DEFAULT '' COMMENT '头像',
                          `bio` varchar(4096) NOT NULL DEFAULT '' COMMENT '详细介绍',
                          `private_hash` varchar(256) NOT NULL DEFAULT '' COMMENT '隐私服务hash',
                          `history_link` varchar(4096) NOT NULL DEFAULT '' COMMENT '历史链接',
                          `profession` varchar(64) NOT NULL DEFAULT '' COMMENT '操作人',
                          `operator` varchar(64) NOT NULL DEFAULT '' COMMENT '操作人',
                          `gender` tinyint(4) NOT NULL DEFAULT '0' COMMENT '性别，0：无性别，1，男 2，女',
                          `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                          `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
                          PRIMARY KEY (`id`),
                          KEY `idx_member_id` (`member_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1771116983469557042 COMMENT='作者基础信息表';

CREATE TABLE `author_manuscript` (
                                     `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                     `member_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'member_id',
                                     `author_id` varchar(64) NOT NULL DEFAULT '' COMMENT '作者id',
                                     `author_name` varchar(256) NOT NULL DEFAULT '' COMMENT '作者名称',
                                     `chapter_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '章节数量',
                                     `sku_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '商品数量',
                                     `yesterday_upvote_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '昨天点赞数',
                                     `7_day_upvote_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '7天点赞数',
                                     `30d_upvote_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '30天点赞数',
                                     `agg_upvote_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '汇总点赞数',
                                     `yesterday_comment_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '昨天评论数',
                                     `7_day_comment_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '7天评论数',
                                     `30d_comment_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '30天评论数',
                                     `agg_comment_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '汇总天评论数',
                                     `p_date` varchar(64) NOT NULL DEFAULT '' COMMENT '时间',
                                     `test_type` int(8) NOT NULL DEFAULT '0' COMMENT '实验是否加和',
                                     PRIMARY KEY (`id`),
                                     KEY `idx_member_id` (`member_id`),
                                     KEY `idx_author_id` (`author_id`),
                                     KEY `idx_p_date` (`p_date`),
                                     KEY `idx_test_type` (`test_type`),
                                     UNIQUE KEY `uniq_author_manuscript` (`member_id`,`test_type`,`p_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=5910001 COMMENT='内容盐选作者文稿页集市汇总表 (每日全量)';

CREATE TABLE `author_works_active` (
                                       `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                       `member_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'member_id',
                                       `author_id` varchar(64) NOT NULL DEFAULT '' COMMENT '作者id',
                                       `author_name` varchar(256) NOT NULL DEFAULT '' COMMENT '作者名称',
                                       `chapter_word_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '章节字数',
                                       `press_month_works_word_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '按月作品字数',
                                       `total_works_word_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '总的作品字数',
                                       `upvote_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '点赞数',
                                       `comment_cnt` int(32) NOT NULL DEFAULT '0' COMMENT '评论数',
                                       `con_0601_wordcount` int(32) NOT NULL DEFAULT '0' COMMENT '稿件0601之前字数',
                                       `con_total_wordcount` int(32) NOT NULL DEFAULT '0' COMMENT '稿件总字数',
                                       `p_date` varchar(64) NOT NULL DEFAULT '' COMMENT '时间',
                                       `test_type` int(8) NOT NULL DEFAULT '0' COMMENT '实验是否加和',
                                       PRIMARY KEY (`id`),
                                       KEY `idx_member_id` (`member_id`),
                                       KEY `idx_author_id` (`author_id`),
                                       KEY `idx_test_type` (`test_type`),
                                       KEY `idx_order_pdate` (`p_date`),
                                       UNIQUE KEY `uniq_author_works_active` (`member_id`,`test_type`,`p_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=5880001 COMMENT='内容盐选作者作品数应用数据表 (每日全量)';

CREATE TABLE `contribution` (
                                `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                                `member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '作者id',
                                `article_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '文本id',
                                `title` varchar(256) NOT NULL DEFAULT '' COMMENT '标题',
                                `introduction` varchar(1024) NOT NULL DEFAULT '' COMMENT '稿件简介',
                                `instruction` varchar(1024) NOT NULL DEFAULT '' COMMENT '作品导语',
                                `content_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '关联站内内容id',
                                `content_type` int(10) NOT NULL DEFAULT '0' COMMENT '关联站内内容类型',
                                `content_source` int(10) NOT NULL DEFAULT '0' COMMENT '站内内容来源',
                                `producer` varchar(256) NOT NULL DEFAULT '' COMMENT '负责的制作人',
                                `contribution_status` bigint(20) NOT NULL DEFAULT '0' COMMENT '稿件状态',
                                `is_long` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否为长短篇',
                                `remark` varchar(256) NOT NULL DEFAULT '' COMMENT '备注',
                                `parent_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '父稿件id',
                                `contribution_index` int(10) NOT NULL DEFAULT '0' COMMENT '稿件顺序id',
                                `clue_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '线索id',
                                `upload_by` varchar(256) NOT NULL DEFAULT '' COMMENT '上传人',
                                `file_url` varchar(256) NOT NULL DEFAULT '' COMMENT '文件链接',
                                `is_plagiarized` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否抄袭',
                                `submit_at` bigint(20) NOT NULL DEFAULT '0' COMMENT '投稿时间',
                                `series_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '系列ID',
                                `online_url` varchar(256) NOT NULL DEFAULT '' COMMENT '上架链接',
                                `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                `review_at` bigint(20) NOT NULL DEFAULT '0' COMMENT '审稿时间',
                                `submit_account` varchar(32) NOT NULL DEFAULT '' COMMENT '发布账号member_id',
                                `reject_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '拒稿理由',
                                `review_status` int(11) NOT NULL DEFAULT '0' COMMENT '审核状态',
                                `primary_producer` varchar(32) NOT NULL DEFAULT '' COMMENT '初审制作人',
                                `clue_type` int(32) NOT NULL DEFAULT '0' COMMENT '线索类型：1盐选个人2盐选机构3外采个人4外采机构',
                                PRIMARY KEY (`id`),
                                KEY `idx_member_id` (`member_id`),
                                KEY `idx_content_id` (`content_id`),
                                KEY `idx_clue_id` (`clue_id`),
                                KEY `idx_parent_id` (`parent_id`,`contribution_status`,`contribution_index`),
                                KEY `idx_clue_id_created_at` (`clue_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1771117406028944689 COMMENT='稿件表';

CREATE TABLE `operate_log` (
                               `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                               `biz_id` varchar(64) NOT NULL DEFAULT '' COMMENT '业务ID',
                               `biz_name` varchar(32) NOT NULL DEFAULT '0' COMMENT '业务方名称',
                               `stash_value` varchar(2048) NOT NULL DEFAULT '' COMMENT '数据快照',
                               `change_value` varchar(2048) NOT NULL DEFAULT '' COMMENT '更新后的数据快照',
                               `operator` varchar(128) NOT NULL DEFAULT '' COMMENT '操作人',
                               `operate_mark` varchar(1024) NOT NULL DEFAULT '' COMMENT '操作日志信息(核心)',
                               `operate_type` int(11) NOT NULL DEFAULT '0' COMMENT '操作类型',
                               `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                               `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
                               PRIMARY KEY (`id`),
                               KEY `idx_operate_type_biz_id` (`operate_type`,`biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=3337462 COMMENT='日志表';

CREATE TABLE `serial_story` (
                                `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                                `member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '作者id',
                                `content_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '内容id',
                                `content_type` int(2) NOT NULL DEFAULT '0' COMMENT '内容类型',
                                `serial_status` int(2) NOT NULL DEFAULT '0' COMMENT '连载状态',
                                `published_at` bigint(20) NOT NULL DEFAULT '0' COMMENT '内容发布时间',
                                `is_deleted` int(2) NOT NULL DEFAULT '0' COMMENT '是否删除',
                                `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                PRIMARY KEY (`id`),
                                KEY `idx_member_id` (`member_id`),
                                UNIQUE KEY `uniq_content` (`content_id`,`content_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1620001 COMMENT='连载内容表';

CREATE TABLE `contribution_ext` (
                                    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                                    `contribution_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '稿件id',
                                    `category_type` int(10) NOT NULL DEFAULT '0' COMMENT '内容分类',
                                    `tags` varchar(1024) NOT NULL DEFAULT '0' COMMENT '标签',
                                    `channel_type` int(10) NOT NULL DEFAULT '0' COMMENT '男女频',
                                    `leading_role` varchar(512) NOT NULL DEFAULT '' COMMENT '主角名称',
                                    `author_file_url` varchar(256) NOT NULL DEFAULT '' COMMENT '作者上传作品url',
                                    `producer_file_url` varchar(256) NOT NULL DEFAULT '' COMMENT '制作人上传作品url',
                                    `accounts` varchar(512) NOT NULL DEFAULT '' COMMENT '发布账号',
                                    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                    `recommend_text` text NOT NULL COMMENT '改稿文字建议',
                                    `recommend_type` int(10) NOT NULL DEFAULT '0' COMMENT '改稿建议类型',
                                    `is_test` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否测试',
                                    `contract_no` varchar(128) NOT NULL DEFAULT '' COMMENT '买断合同号',
                                    `buy_out_price` bigint(20) NOT NULL DEFAULT '0' COMMENT '买断金额',
                                    `buy_out_status` int(32) NOT NULL DEFAULT '0' COMMENT '买断状态',
                                    `buy_out_reason` varchar(256) NOT NULL DEFAULT '' COMMENT '暂无意向原因',
                                    `buyout_confirmation_status` int(32) NOT NULL DEFAULT '0' COMMENT '买断未成年承诺书状态, 0 不涉及, 1 待发起, 2 签署中, 3 已签署, 4 已归档, -1 异常',
                                    `primary_buy_out_level` int(32) NOT NULL DEFAULT '0' COMMENT '邀请买断等级',
                                    `final_buy_out_level` int(32) NOT NULL DEFAULT '0' COMMENT '最终买断等级',
                                    `contract_sign_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '归档日期',
                                    `is_agree_free_to_vip` int(32) NOT NULL DEFAULT '0' COMMENT '是否同意授权免转付',
                                    `reject_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '拒稿时间',
                                    `create_channel` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '稿件创建渠道1：web，2：H5',
                                    `hotspot_word` varchar(20) NOT NULL DEFAULT '' COMMENT '热点词',
                                    `buy_out_public_range` varchar(255) NOT NULL DEFAULT '' COMMENT '稿件流通列表',
                                    `source_certificate` varchar(256) NOT NULL DEFAULT '' COMMENT '来源证明',
                                    `review_source` int(32) NOT NULL DEFAULT '0' COMMENT '审核来源',
                                    `check_source_certificate` int(8) NOT NULL DEFAULT '0' COMMENT '校验来源证明，1：已校验',
                                    `safe_audit_task_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '安审任务ID',
                                    `transform_section_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '性转小节id',
                                    PRIMARY KEY (`id`),
                                    UNIQUE KEY `uniq_contribution_id` (`contribution_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=2670001 COMMENT='稿件额外信息表';

CREATE TABLE `works` (
                         `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                         `member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '作者id',
                         `title` varchar(256) NOT NULL DEFAULT '' COMMENT '标题',
                         `introduction` varchar(1024) NOT NULL DEFAULT '' COMMENT '稿件简介',
                         `instruction` varchar(1024) NOT NULL DEFAULT '' COMMENT '作品导语',
                         `category_type` int(10) NOT NULL DEFAULT '0' COMMENT '内容分类',
                         `tags` varchar(1024) NOT NULL DEFAULT '0' COMMENT '标签',
                         `channel_type` int(10) NOT NULL DEFAULT '0' COMMENT '男女频',
                         `leading_role` varchar(512) NOT NULL DEFAULT '' COMMENT '主角名称',
                         `expected_word_count` int(32) NOT NULL DEFAULT '0' COMMENT '预计作品字数（万）',
                         `work_detail_outline` varchar(10000) NOT NULL DEFAULT '' COMMENT '作品详纲',
                         `character_biography` varchar(10000) NOT NULL DEFAULT '' COMMENT '人物小传',
                         `content_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '关联站内内容id',
                         `content_type` int(10) NOT NULL DEFAULT '0' COMMENT '关联站内内容类型',
                         `content_source` int(10) NOT NULL DEFAULT '0' COMMENT '站内内容来源',
                         `is_agree_free_to_vip` int(32) NOT NULL DEFAULT '0' COMMENT '是否同意授权免转付',
                         `primary_producer` varchar(32) NOT NULL DEFAULT '' COMMENT '初审制作人',
                         `producer` varchar(256) NOT NULL DEFAULT '' COMMENT '负责的制作人',
                         `space_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否为长篇1：长篇，2：短篇',
                         `clue_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '线索id',
                         `clue_type` int(32) NOT NULL DEFAULT '0' COMMENT '线索类型：1盐选个人2盐选机构3外采个人4外采机构',
                         `is_submit` int(32) NOT NULL DEFAULT '0' COMMENT '是否有稿件已提交',
                         `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                         `is_test` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否测试',
                         `series_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '系列ID',
                         `last_submit_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '最后一次提交时间',
                         `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                         `is_deal` int(10) NOT NULL DEFAULT '0' COMMENT '作者是否上传稿件',
                         `source_certificate` varchar(256) NOT NULL DEFAULT '' COMMENT '来源证明',
                         `check_source_certificate` int(8) NOT NULL DEFAULT '0' COMMENT '校验来源证明，1：已校验',
                         `is_delete` int(8) NOT NULL DEFAULT '0' COMMENT '是否删除，0：未删除，1：删除',
                         `to_be_film` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否影视意向 0: 否 1:是',
                         PRIMARY KEY (`id`),
                         KEY `idx_member_id` (`member_id`),
                         KEY `idx_content_id` (`content_id`),
                         KEY `idx_clue_id` (`clue_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1771117270493783346 COMMENT='投稿作品表';

CREATE TABLE `clue` (
                        `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                        `clue_name` varchar(128) NOT NULL DEFAULT '' COMMENT '线索名称',
                        `clue_type` int(32) NOT NULL DEFAULT '0' COMMENT '线索类型',
                        `clue_step` int(32) NOT NULL DEFAULT '0' COMMENT '线索节点步骤',
                        `clue_status` int(32) DEFAULT '0' COMMENT '线索状态',
                        `author_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '线索结算主作者ID',
                        `member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '线索结算主作者-站内用户ID',
                        `domain_type` int(8) NOT NULL DEFAULT '0' COMMENT '投稿分类[1：故事，2：知识，4：男频，5：女频]',
                        `domains` varchar(128) NOT NULL DEFAULT '' COMMENT '投稿分类一级分类列表',
                        `producer` bigint(20) NOT NULL DEFAULT '0' COMMENT '线索归属制作人id',
                        `share_producer` varchar(1024) NOT NULL DEFAULT '' COMMENT '线索分享人',
                        `tag` varchar(512) NOT NULL DEFAULT '' COMMENT '标签',
                        `contract_no` varchar(256) NOT NULL DEFAULT '' COMMENT '结算方合同编号',
                        `contract_no_name` varchar(256) NOT NULL DEFAULT '' COMMENT '合同名称',
                        `contract_name` varchar(256) NOT NULL DEFAULT '' COMMENT '结算方名称',
                        `pre_id_card` varchar(256) NOT NULL DEFAULT '' COMMENT '身份证正面照片',
                        `back_id_card` varchar(256) NOT NULL DEFAULT '' COMMENT '身份证背面照片',
                        `account_bank` varchar(256) NOT NULL DEFAULT '' COMMENT '开户银行',
                        `bank_address` varchar(256) NOT NULL DEFAULT '' COMMENT '开户银行地址',
                        `bank_union_number` varchar(256) NOT NULL DEFAULT '' COMMENT '开户银行支行的联行号',
                        `contact_address` varchar(256) NOT NULL DEFAULT '' COMMENT '联系地址',
                        `bankcard` varchar(256) NOT NULL DEFAULT '' COMMENT '银行卡正面图片地址',
                        `back_bankcard` varchar(256) NOT NULL DEFAULT '' COMMENT '银行卡背面图片地址',
                        `biz_license` varchar(256) NOT NULL DEFAULT '' COMMENT '营业执照',
                        `account_license` varchar(256) NOT NULL DEFAULT '' COMMENT '开户证明',
                        `email` varchar(128) NOT NULL DEFAULT '' COMMENT '线索关联email',
                        `exclusive_level` int(8) NOT NULL DEFAULT '0' COMMENT '用户专属等级',
                        `settlement_contract` int(8) NOT NULL DEFAULT '0' COMMENT '结算是否有合同',
                        `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                        `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                        `prepayment_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '经纪约预付款',
                        `tag_updated_at` bigint(20) NOT NULL DEFAULT '0' COMMENT '标签流转更新时间',
                        PRIMARY KEY (`id`),
                        KEY `idx_member_id_clue_type` (`member_id`,`clue_type`),
                        KEY `idx_author_id` (`author_id`),
                        KEY `idx_created_at` (`created_at`),
                        KEY `idx_tag_created` (`tag`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=12820000 COMMENT='线索表';

CREATE TABLE `contribution_answer_relation` (
                                                `answer_token` varchar(64) NOT NULL DEFAULT '0' COMMENT '回答token',
                                                `answer_id` bigint(64) NOT NULL DEFAULT '0' COMMENT '回答id',
                                                `question_token` bigint(64) NOT NULL DEFAULT '0' COMMENT '问题token',
                                                `contribution_id` bigint(64) NOT NULL DEFAULT '0' COMMENT '稿件id',
                                                `member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'memberID',
                                                `creator_level` int(8) NOT NULL DEFAULT '0' COMMENT '创作者等级',
                                                `7d_upvote_cnt` bigint(20) NOT NULL DEFAULT '0' COMMENT '点赞数7日增量',
                                                `30d_upvote_cnt` bigint(20) NOT NULL DEFAULT '0' COMMENT '点赞数30日增量',
                                                `total_upvote_cnt` bigint(20) NOT NULL DEFAULT '0' COMMENT '点赞数总量',
                                                `answer_online_time` bigint(64) NOT NULL DEFAULT '0' COMMENT '回答创建时间',
                                                `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                PRIMARY KEY (`contribution_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='稿件关联回答点赞表';

CREATE TABLE `clue_author_relation_biz` (
                                            `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                            `clue_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '线索主键ID',
                                            `author_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '作者主键ID',
                                            `show_type` int(32) NOT NULL DEFAULT '0' COMMENT '作者信息展示类型',
                                            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
                                            `is_main` int(32) NOT NULL DEFAULT '0' COMMENT '是否线索结算作者',
                                            PRIMARY KEY (`id`),
                                            KEY `idx_author_id` (`author_id`),
                                            KEY `idx_clue_id_created_at` (`clue_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=2820001 COMMENT='线索作者关系表';

CREATE TABLE `contract` (
                            `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                            `clue_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '线索ID',
                            `contribution_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '稿件ID',
                            `section_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '小节ID',
                            `contract_no` varchar(256) NOT NULL DEFAULT '' COMMENT '对应的合同编号',
                            `producer_name` varchar(256) NOT NULL DEFAULT '' COMMENT '制作人名',
                            `sign_status` int(32) NOT NULL DEFAULT '0' COMMENT '签约状态 0: 合作邀约 1: 待签约 2: 签约中 3: 已签约 4: 暂不签约 5:签约链接过期',
                            `is_limited_free` int(8) NOT NULL DEFAULT '0' COMMENT '是否限时免费 0: 否, 1：是',
                            `is_copyright` int(8) NOT NULL DEFAULT '0' COMMENT '是否有著作权 0: 否, 1：是',
                            `authorization_nature` int(32) NOT NULL DEFAULT '0' COMMENT '授权性质 0: 独家 1: 非独家 2: 排他',
                            `authorization_rights` varchar(512) NOT NULL DEFAULT '' COMMENT '授权权利',
                            `sublicense` int(32) NOT NULL DEFAULT '0' COMMENT '转授权 0: 无 1: 有',
                            `protection_rights` int(32) NOT NULL DEFAULT '0' COMMENT '维权权利 0: 无 1: 有',
                            `divided_ratio` varchar(128) NOT NULL DEFAULT '' COMMENT '分成比例',
                            `descript` varchar(512) NOT NULL DEFAULT '' COMMENT '描述',
                            `payment_method` int(32) NOT NULL DEFAULT '0' COMMENT '结算方式 0: 代扣代缴 1: 云账户',
                            `prepayment_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '经纪约预付款',
                            `cloud_account_id` varchar(128) NOT NULL DEFAULT '' COMMENT '云账户ID',
                            `vendor_id` varchar(128) NOT NULL DEFAULT '' COMMENT '供应商ID',
                            `cdp_vendor_name` varchar(128) NOT NULL DEFAULT '' COMMENT '费控供应商名',
                            `sign_id` varchar(128) NOT NULL DEFAULT '' COMMENT '电子签ID',
                            `contract_status` int(32) NOT NULL DEFAULT '0' COMMENT '流转状态',
                            `message` varchar(256) NOT NULL DEFAULT '' COMMENT '错误信息',
                            `contract_type` int(32) NOT NULL DEFAULT '0' COMMENT '合同类型 0: 主协议 1: 补充协议',
                            `sign_type` int(32) NOT NULL DEFAULT '0' COMMENT '签约类型',
                            `efficient_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '合同确认时间(时间戳)',
                            `contract_period_year` int(32) NOT NULL DEFAULT '0' COMMENT '合同期限',
                            `contract_link` varchar(256) NOT NULL DEFAULT '' COMMENT '合同链接',
                            `oss_link` varchar(256) NOT NULL DEFAULT '' COMMENT '合同 oss 链接',
                            `encrypt_link` varchar(256) NOT NULL DEFAULT '' COMMENT '打码合同链接',
                            `is_hand_encrypt` int(32) NOT NULL DEFAULT '0' COMMENT '是否手动加密',
                            `template_id` int(32) NOT NULL DEFAULT '0' COMMENT '模版id',
                            `voucher_resource_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '电子存证资源ID',
                            `archive_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '归档时间',
                            `data_source` int(32) NOT NULL DEFAULT '0' COMMENT '0:线上签约 1:历史数据',
                            `is_efficient` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否有效 0:有效 1:无效',
                            `is_deleted` int(32) NOT NULL DEFAULT '0' COMMENT '1:已删除',
                            `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                            `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                            `contract_language` varchar(50) NOT NULL DEFAULT '' COMMENT '授权语言',
                            `area` varchar(20) NOT NULL DEFAULT '' COMMENT '授权地域范围',
                            `authorized_party` varchar(256) NOT NULL DEFAULT '' COMMENT '被授权方',
                            `source_certificate` varchar(256) NOT NULL DEFAULT '' COMMENT '证明来源',
                            `contract_purpose` bigint(20) NOT NULL DEFAULT '0' COMMENT '签署目的',
                            PRIMARY KEY (`id`),
                            KEY `idx_clue_id` (`clue_id`),
                            KEY `idx_contract_status` (`contract_status`),
                            KEY `idx_section_status` (`section_id`,`sign_status`),
                            KEY `idx_sign_status_type` (`clue_id`,`sign_status`,`contract_type`),
                            KEY `idx_contribution_id_sign_type` (`contribution_id`,`sign_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1770962006968665393 COMMENT='合同表';

CREATE TABLE `high_quality_answer` (
                                       `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                                       `question_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '问题标题',
                                       `answer_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评论时间',
                                       `author_answer_token` bigint(20) NOT NULL DEFAULT '0' COMMENT '作者评论token',
                                       `author_answer_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '作者评论id',
                                       `answer_show_num` bigint(20) NOT NULL DEFAULT '0' COMMENT '曝光数量',
                                       `approve_week` bigint(20) NOT NULL DEFAULT '0' COMMENT '7天赞同量',
                                       `approve_month` bigint(20) NOT NULL DEFAULT '0' COMMENT '30天赞同量',
                                       `approve_excavate` bigint(20) NOT NULL DEFAULT '0' COMMENT '挖掘赞同量',
                                       `approve` bigint(20) NOT NULL DEFAULT '0' COMMENT '总赞同量',
                                       `read_num` bigint(20) NOT NULL DEFAULT '0' COMMENT '有效阅读数',
                                       `ctr` decimal(16,6) NOT NULL DEFAULT '0' COMMENT 'ctr',
                                       `npr` decimal(16,6) NOT NULL DEFAULT '0' COMMENT '负正比',
                                       `word_num` bigint(20) NOT NULL DEFAULT '0' COMMENT '评论字数',
                                       `koc` int(8) NOT NULL DEFAULT '0' COMMENT '是否koc投放，1投放，0未投放',
                                       `topic_id` varchar(512) NOT NULL DEFAULT '0' COMMENT 'topicId',
                                       `excavate_status` int(8) NOT NULL DEFAULT '0' COMMENT '挖掘状态',
                                       `excavate_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '挖掘时间',
                                       `reason` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
                                       `create_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                       `update_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                       `contribute_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '投稿id',
                                       `contribute_owner` varchar(64) NOT NULL DEFAULT '' COMMENT '投稿负责人',
                                       `clue_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '线索id',
                                       `clue_owner` varchar(64) NOT NULL DEFAULT '' COMMENT '线索负责人',
                                       `operator` int(8) NOT NULL DEFAULT '0' COMMENT '操作',
                                       `operator_owner` varchar(64) NOT NULL DEFAULT '' COMMENT '操作人',
                                       `content_type` int(8) NOT NULL DEFAULT '0' COMMENT '内容类型',
                                       `distribute_status` int(8) NOT NULL DEFAULT '0' COMMENT '分配状态',
                                       `member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'member_id',
                                       `producer` varchar(64) NOT NULL DEFAULT '' COMMENT '制作人',
                                       `clue_sign` int(8) NOT NULL DEFAULT '0' COMMENT '是否签约 1：未签约，2：已签约',
                                       `is_delete` int(8) NOT NULL DEFAULT '0' COMMENT '是否删除 0：未删除，1：已删除',
                                       `high_quality_content_type` int(8) NOT NULL DEFAULT '0' COMMENT '挖掘内容类型 1：回答，2：文章',
                                       `content_grade` int(8) NOT NULL DEFAULT '0' COMMENT '等级 1:S级 2:A级 3:B级',
                                       `preliminary_status` int(8) NOT NULL DEFAULT '0' COMMENT '初审状态 0:无需初审 1:待初审 2:已初审',
                                       `three_day_show` bigint(20) NOT NULL DEFAULT '0' COMMENT '三天曝光',
                                       `three_day_upvote` bigint(20) NOT NULL DEFAULT '0' COMMENT '三天赞同',
                                       `three_day_comment` bigint(20) NOT NULL DEFAULT '0' COMMENT '三天评论',
                                       `seven_day_show` bigint(20) NOT NULL DEFAULT '0' COMMENT '七天曝光',
                                       `seven_day_comment` bigint(20) NOT NULL DEFAULT '0' COMMENT '七天评论',
                                       `contribution_status` int(11) NOT NULL DEFAULT '0' COMMENT '审稿状态',
                                       PRIMARY KEY (`id`),
                                       KEY `idx_excavate_status` (`excavate_status`),
                                       KEY `idx_clue_id` (`clue_id`),
                                       KEY `idx_answer_time` (`answer_time`),
                                       KEY `idx_contribute_id` (`contribute_id`),
                                       KEY `idx_author_answer_id` (`author_answer_id`),
                                       KEY `idx_content_type` (`content_type`),
                                       KEY `idx_distribute_status` (`distribute_status`),
                                       KEY `idx_member_id` (`member_id`),
                                       KEY `idx_producer` (`producer`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=2610001 COMMENT='优质回答表';

CREATE TABLE `business_clue_relation` (
                                          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                                          `business_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '商品id',
                                          `business_type` int(2) NOT NULL DEFAULT '0' COMMENT '商品类型',
                                          `section_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '章节id',
                                          `clue_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'clue_id',
                                          `sku_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'sku_id',
                                          `relation_type` bigint(20) NOT NULL DEFAULT '0' COMMENT '关联类型 0:默认值 1:商品 2:小节',
                                          `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                          `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                          PRIMARY KEY (`id`),
                                          KEY `idx_business_id` (`business_id`),
                                          KEY `idx_section_id` (`section_id`),
                                          KEY `idx_sku_id` (`sku_id`),
                                          KEY `idx_clue_id` (`clue_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=2790001 COMMENT='内容-线索关联表';

CREATE TABLE `contract_section_relation` (
                                             `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                             `contract_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '合同 id',
                                             `section_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '小节 id',
                                             `content_type` int(8) NOT NULL DEFAULT '0' COMMENT '记录的小节类型 0 短篇, 1 长篇',
                                             `business_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '长篇的 id, 长篇类型才有该值',
                                             `record_status` int(32) NOT NULL DEFAULT '0' COMMENT '补录状态 0 未补录到 contract 表, 1 已补录到 contract 表',
                                             `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                             `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                             PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=13390000 COMMENT='合同小节关系表';

CREATE TABLE `free_content` (
                                `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                                `content_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '内容id',
                                `content_token` bigint(20) NOT NULL DEFAULT '0' COMMENT '内容token',
                                `content_type` int(2) NOT NULL DEFAULT '0' COMMENT '内容类型 1:回答 2:文章',
                                `member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '作者member_id',
                                `content_source` int(2) NOT NULL DEFAULT '0' COMMENT '内容来源 1:签约作者；2:重点问题',
                                `contribution_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '稿件id',
                                `contribution_status` int(2) NOT NULL DEFAULT '0' COMMENT '稿件状态',
                                `work_status` int(2) NOT NULL DEFAULT '0' COMMENT '作品状态',
                                `release_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '内容发布时间',
                                `update_times` int(5) NOT NULL DEFAULT '0' COMMENT '更新次数',
                                `content_updated_at` bigint(20) NOT NULL DEFAULT '0' COMMENT '内容更新时间',
                                `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                PRIMARY KEY (`id`),
                                KEY `idx_content_token` (`content_token`),
                                KEY `idx_content_id` (`content_id`),
                                UNIQUE KEY `uniq_content` (`content_id`,`content_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=240001 COMMENT='免费期内容';

CREATE TABLE `works_contribution_relation` (
                                               `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                                               `work_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '投稿作品id',
                                               `contribution_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '投稿章节id',
                                               `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                               `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                               `idx` int(10) NOT NULL DEFAULT '0' COMMENT '投稿顺序',
                                               PRIMARY KEY (`id`),
                                               KEY `idx_work_id` (`work_id`),
                                               UNIQUE KEY `uniq_contribution_id` (`contribution_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=3180001 COMMENT='作品和章节关系表';

CREATE TABLE `contract_doc_record` (
                                       `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
                                       `member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '站内用户ID',
                                       `url_token` varchar(64) NOT NULL DEFAULT '' COMMENT '用户token',
                                       `price` varchar(32) NOT NULL DEFAULT '' COMMENT '金额',
                                       `dynamic_date` varchar(256) NOT NULL DEFAULT '' COMMENT '时间节点',
                                       `batch` varchar(32) NOT NULL DEFAULT '' COMMENT '批次',
                                       `template` varchar(256) NOT NULL DEFAULT '' COMMENT '模板文件版本',
                                       `table_row` bigint(20) NOT NULL DEFAULT '0' COMMENT '表格行数',
                                       `doc_page` bigint(20) NOT NULL DEFAULT '0' COMMENT 'doc页数',
                                       `is_success` bigint(20) NOT NULL DEFAULT '0' COMMENT '是否成功',
                                       `send_at` bigint(20) NOT NULL DEFAULT '0' COMMENT '发送时间',
                                       `send_email` varchar(128) NOT NULL DEFAULT '' COMMENT '发送邮箱',
                                       `contract_status` bigint(20) NOT NULL DEFAULT '0' COMMENT '合同状态',
                                       `contract_id` varchar(32) NOT NULL DEFAULT '' COMMENT '合同编号',
                                       `sign_id` varchar(32) NOT NULL DEFAULT '' COMMENT '电子签id',
                                       `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                       `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                       PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=600001 COMMENT='经纪约签约doc文件发送记录表';

CREATE TABLE `series` (
                          `id` bigint(20) NOT NULL COMMENT '主键',
                          `series_name` varchar(64) NOT NULL DEFAULT '' COMMENT '系列名称',
                          `member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建人member_id',
                          `introduce` varchar(255) NOT NULL DEFAULT '' COMMENT '简介',
                          `detail` varchar(1024) NOT NULL DEFAULT '' COMMENT '详情',
                          `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                          `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                          PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系列表';

CREATE TABLE `series_content_relation` (
                                           `id` bigint(20) NOT NULL COMMENT '主键',
                                           `series_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '系列ID',
                                           `content_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '作品ID',
                                           `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                           `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                           PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系列内容关系表';

CREATE TABLE `task_contract_relation` (
                                          `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                          `contract_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '合同 id',
                                          `task_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '批量合同任务 id',
                                          `excel_index` bigint(20) NOT NULL DEFAULT '0' COMMENT '批量合同任务对应的 excel 中的位置',
                                          `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                          `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
                                          PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1740001 COMMENT='合同批量任务与合同的关系表';

CREATE TABLE `works_sku_relation` (
                                      `id` bigint(20) NOT NULL COMMENT '主键ID',
                                      `work_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '作品ID',
                                      `well_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '课程ID',
                                      `sku_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'skuID',
                                      `chapter_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'chapter_id',
                                      `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                      `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
                                      PRIMARY KEY (`id`),
                                      UNIQUE KEY `uniq_work_id` (`work_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='作品sku关系表';

CREATE TABLE `async_task` (
                              `id` bigint(20) NOT NULL COMMENT '主键ID',
                              `track_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '幂等ID',
                              `task_type` varchar(128) NOT NULL DEFAULT '' COMMENT '任务类型',
                              `task_status` int(32) NOT NULL DEFAULT '0' COMMENT '任务状态:  0:未开始，1：已完成，-1:已删除',
                              `task_info` json NOT NULL COMMENT '任务信息',
                              `task_info_ext` mediumtext NOT NULL COMMENT '任务额外信息',
                              `result_info` tinytext NOT NULL COMMENT '任务额外信息',
                              `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                              `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
                              PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='异步任务表';

CREATE TABLE `producer_group_relation` (
                                           `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                           `producer_name` varchar(64) NOT NULL DEFAULT '' COMMENT '制作人名称',
                                           `producer_name_cn` varchar(64) NOT NULL DEFAULT '' COMMENT '制作人中文名',
                                           `email` varchar(64) NOT NULL DEFAULT '' COMMENT '邮箱',
                                           `producer_status` int(8) NOT NULL DEFAULT '0' COMMENT '状态0正常，-1删除',
                                           `group_token` varchar(128) NOT NULL DEFAULT '' COMMENT '组别token',
                                           `nick_name` varchar(64) NOT NULL DEFAULT '' COMMENT '花名',
                                           `name_card` varchar(128) NOT NULL DEFAULT '' COMMENT '个人名片',
                                           `review_tag` varchar(512) NOT NULL DEFAULT '' COMMENT '审稿标签',
                                           `preliminary_review` bigint(20) NOT NULL DEFAULT '0' COMMENT '初审审稿个数',
                                           `first_review` bigint(20) NOT NULL DEFAULT '0' COMMENT '一审审稿个数',
                                           `created_at` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                           `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
                                           `is_assign` int(8) NOT NULL DEFAULT '0' COMMENT '是否接收稿件分配，0：不接收，1接收',
                                           PRIMARY KEY (`id`),
                                           KEY `idx_group_token` (`group_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1860001 COMMENT='制作人-组别关系表';

CREATE TABLE `producer_group_config` (
                                         `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                         `group_name` varchar(64) NOT NULL DEFAULT '' COMMENT '组名',
                                         `token` bigint(20) NOT NULL DEFAULT '0' COMMENT 'token',
                                         `group_status` int(8) NOT NULL DEFAULT '0' COMMENT '状态：0正常，-1已删除',
                                         `domains` varchar(1024) NOT NULL DEFAULT '' COMMENT '擅长领域',
                                         `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                         `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
                                         `operator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者信息',
                                         PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=690001 COMMENT='制作人组配置表';

CREATE TABLE `institution_author` (
                                      `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                      `member_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '机构用户id',
                                      `institution_name` varchar(128) NOT NULL DEFAULT '' COMMENT '名称',
                                      `institution_token` varchar(128) NOT NULL DEFAULT '' COMMENT '机构token',
                                      `explanation` text DEFAULT NULL COMMENT '合作说明',
                                      `introduce` text DEFAULT NULL COMMENT '介绍',
                                      `manuscript` mediumtext DEFAULT NULL COMMENT '稿件',
                                      `true_name` varchar(256) NOT NULL DEFAULT '' COMMENT '姓名',
                                      `wechat_no` varchar(256) NOT NULL DEFAULT '' COMMENT '微信',
                                      `phone_no` varchar(128) NOT NULL DEFAULT '' COMMENT '手机号',
                                      `social_credit_code` varchar(64) NOT NULL DEFAULT '' COMMENT '统一社会信用代码',
                                      `legal_private_data` varchar(128) NOT NULL DEFAULT '' COMMENT '法人隐私数据',
                                      `sign_people_type` int(8) NOT NULL DEFAULT '0' COMMENT '签约代表类型，1：法人代表；2：授权代表',
                                      `sign_people_credente_type` int(8) NOT NULL DEFAULT '0' COMMENT '签约代表证件类型，1：身份证',
                                      `sign_private_data` varchar(128) NOT NULL DEFAULT '' COMMENT '签约人隐私数据',
                                      `sign_authorization_file` varchar(128) NOT NULL DEFAULT '' COMMENT '签约代表授权文件',
                                      `is_modify` int(8) NOT NULL DEFAULT '0' COMMENT '是否修改信息',
                                      `check_result` int(8) NOT NULL DEFAULT '0' COMMENT '四要素校验结果,0:待校验,1:四要素yes,2:四要素no',
                                      `review_status` int(8) NOT NULL DEFAULT '0' COMMENT '审核状态,0:待审核,1:审核通过，2：审核不通过',
                                      `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                      `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                      PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1770881554472367409 COMMENT='作者基础信息表';

CREATE TABLE `contract_template` (
                                     `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                     `download_url` varchar(256) NOT NULL DEFAULT '' COMMENT '合同模版下载链接',
                                     `encrypt_position` varchar(1024) NOT NULL DEFAULT '' COMMENT '打码坐标列表',
                                     `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                     `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                     PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=720001 COMMENT='合同模版表';

CREATE TABLE `contract_task` (
                                 `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                 `word_file` varchar(128) NOT NULL DEFAULT '' COMMENT '表格文件路径',
                                 `zip_file` varchar(128) NOT NULL DEFAULT '' COMMENT '附件路径',
                                 `task_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '任务状态 0: 未开始 1: 执行中 2: 执行完成',
                                 `operator` varchar(128) NOT NULL DEFAULT '' COMMENT '操作人',
                                 `task_type` int(8) NOT NULL DEFAULT '0' COMMENT '任务类型 0 买断, 1 koc 合同',
                                 `ext_msg` mediumtext DEFAULT NULL COMMENT '额外信息 json 格式字符串',
                                 `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                 `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1620001 COMMENT='合同批量创建任务表';

CREATE TABLE `contract_log` (
                                `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                `contract_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '业务ID',
                                `operator` varchar(128) NOT NULL DEFAULT '' COMMENT '操作人',
                                `operate_type` int(11) NOT NULL DEFAULT '0' COMMENT '操作类型',
                                `reason` varchar(128) NOT NULL DEFAULT '' COMMENT '原因',
                                `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
                                PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=690001 COMMENT='合同日志表';

CREATE TABLE `contract_appendix` (
                                     `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                     `contract_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '合同id',
                                     `title` varchar(128) NOT NULL DEFAULT '' COMMENT '标题',
                                     `finished_count` varchar(256) NOT NULL DEFAULT '' COMMENT '完稿字数',
                                     `word_count` varchar(128) NOT NULL DEFAULT '' COMMENT '字数',
                                     `lower_cost` varchar(128) NOT NULL DEFAULT '' COMMENT '金额小写',
                                     `capital_cost` varchar(128) NOT NULL DEFAULT '' COMMENT '金额大写',
                                     `file_name` varchar(128) NOT NULL DEFAULT '' COMMENT '文件名称',
                                     `file_link` varchar(128) NOT NULL DEFAULT '' COMMENT '附件路径',
                                     `deliver_time` varchar(256) NOT NULL DEFAULT '' COMMENT '交付时间',
                                     `due_time` bigint(20) NOT NULL DEFAULT '0' COMMENT '交付时间',
                                     `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                     `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                     PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=930001 COMMENT='合同附件表';

CREATE TABLE `clue_author_relation` (
                                        `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                        `clue_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '线索主键ID',
                                        `author_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '作者主键ID',
                                        `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                        `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
                                        PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=300001 COMMENT='线索作者关系表';

CREATE TABLE `author_ext` (
                              `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
                              `author_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '作者ID',
                              `gender` int(32) NOT NULL DEFAULT '0' COMMENT '性别',
                              `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                              `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                              PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30001 COMMENT='作者扩展表';